### ISSUE TITLE
db-hint

### ISSUE THREAD

**Issue by vitaly-t** [bocoup/pombot#17]
about this: https://github.com/bocoup/pombot/blob/864ac9720fbf4d7a9230e521bb18d94856416e96/src/sql/index.js

check out methods within the [utils](http://vitaly-t.github.io/pg-promise/utils.html) namespace, and particularly [enumSql](http://vitaly-t.github.io/pg-promise/utils.html#.enumSql), because that's what you are replacing there ;)

**Comment by vitaly-t** [comment]
Just so, with options set to `{recursive: true}`, you can start dumping SQL files into it like there's no tomorrow ;)

**Comment by vitaly-t** [comment]
I mean, the best way to organize it - having folders for table names / entities, and then files within them for the related queries.

**Comment by tkellen** [comment]
I can see the value of that for a larger project but I think a flat namespace for this is fine!

**Comment by vitaly-t** [comment]
Check out [4.6.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.4.6.0) that I just released ;)
