### ISSUE TITLE
activateTeamIntegration should use ON CONFLICT 

### ISSUE THREAD

**Issue by tkellen** [bocoup/pombot#28]
...rather than using a regex to compare a failure message from postgresql
https://github.com/bocoup/pombot/blob/master/src/app.js#L11

`https://github.com/bocoup/pombot/blob/master/src/sql/team_activate_insert.sql` could be:
```sql
INSERT INTO slack_team (
  token,
  slack_id,
  oauth_payload,
  is_active
)
VALUES (
  ${token},
  ${teamId},
  ${payload},
  true
)
ON CONFLICT (token) DO UPDATE is_active=true;
```

**Comment by cowboy** [comment]
I'd love to do that! Except I couldn't get it to work. Are you sure the Postgres server is a new enough version?

**Comment by tkellen** [comment]
Yup! We bumped to 9.5 over the weekend during our scheduled maintenance window.

**Comment by cowboy** [comment]
It looks like it's a new version now. Was it upgraded since Friday?

**Comment by cowboy** [comment]
Ok, thanks, I'll add this in today!
