### ISSUE TITLE
create "install app" button to kick off oauth flow for installing pombot

### ISSUE THREAD

**Issue by tkellen** [bocoup/pombot#4]

**Comment by jennschiffer** [comment]
```<a href="https://slack.com/oauth/authorize?scope=incoming-webhook&client_id=2186729465.48572709424"><img alt="Add to Slack" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x" /></a>```

**Comment by tkellen** [comment]
:+1:
