### ISSUE TITLE
marketplace submission

### ISSUE THREAD

**Issue by jennschiffer** [bocoup/pombot#54]
here are the questions we need to respond to when submitting an app to the marketplace:

updated with checklist:

* [x] support email address
* [x] privacy policy

![screen shot 2016-06-27 at 3 08 37 pm](https://cloud.githubusercontent.com/assets/341305/16392403/b2d31c56-3c79-11e6-8ae9-1169d30de0d0.png)
![screen shot 2016-06-27 at 3 08 49 pm](https://cloud.githubusercontent.com/assets/341305/16392402/b2d14278-3c79-11e6-899c-f4f073794f81.png)
![screen shot 2016-06-27 at 3 09 02 pm](https://cloud.githubusercontent.com/assets/341305/16392404/b2d3c1f6-3c79-11e6-9871-8c28b982560e.png)
![screen shot 2016-06-27 at 3 09 11 pm](https://cloud.githubusercontent.com/assets/341305/16392405/b2d61442-3c79-11e6-9ce3-a61c3de482ff.png)

**Comment by tkellen** [comment]
I just created bots@bocoup.com with jenn/ben/myself as members.
