### ISSUE TITLE
draft privacy policy

### ISSUE THREAD

**Issue by tkellen** [bocoup/pombot#58]
We need a privacy policy to have an app in the slack app store. I'm going to use this issue to track my research around this space. We want something ethical and readable and we need to ensure that we actually adhere to it.

**Comment by tkellen** [comment]
Some prior art:
https://thoughtbot.com/upcase/privacy
https://github.com/Editorially/terms/blob/master/terms.md

**Comment by tkellen** [comment]
Jumping into a few meetings here. I wanted to share out what I have so far. I'll update this note later today as I wrap up the first draft:

# Pombot Terms of Service and Privacy Policy

This is a legally binding contract between you and Bocoup, LLC. Please make sure you read it, because it is important. We’ve tried to make it as clear as possible, but we welcome feedback to <a href="mailto:hello@bocoup.com?subject=Privacy+Policy">hello@bocoup.com.</a>. In addition, we‘ve made these terms available under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-ShareAlike</a> license, so you can use and adapt them as you see fit.

## 1. Definitions

We’re going to use some shorthand to make this easier to read. When we say "service",” we mean the bot you communicate with through Slack. When we say “we,” “us,” or “our,” we mean Bocoup LLC., a Massachusetts corporation. When we say “your content,” we mean any text, sound, graphics or other material which you post, upload, or otherwise share with the service. When we say “terms,” we mean these terms of service.

## 2. Accepting these terms

Please read these terms before using the service. *If you do not agree to these terms, you may not register for the service.* If we make material changes to these terms, we’ll let you know through the service. If you do not agree to those changes, you may discontinue use of the service. If you do not do so within ten days, the revised terms *will* apply to you. 

## 3. Privacy policy

Through usage of the service you will grant us access to your content. We will not share it with any third parties, except as necessary to provide the services offered, to monitor usage, and to improve the service. For example, we may store your information on a third party server such as Amazon Web Services. We may also use your information to send notifications about the service. We will *never* share your personal information with advertisers or send you promotions for unrelated services.

We may be required to disclose your content in order to:

  - comply with the law or legal process;
  - protect or defend our rights or property, or the rights or property of others;
  - enforce these terms; or
  - respond to claims that the content of any material on our system violates the rights of others.

If we must disclose your content in order to comply with the law or legal process, we will inform you via the service as soon as practicable, provided that it is lawful for us to do so.

We may also perform statistical analyses of the collective behavior of our members to improve our service. In addition, we may compile and disclose aggregate information about our users for promotional or other purposes. This information will not contain your content. For example, we might want to disclose that a certain percentage of our users work most frequently in the mornings.

## 4. Copyright and intellectual property

We own our stuff; you own yours.

You retain ownership of all content you post, upload to, or otherwise share on the service. However, by posting, uploading, or sharing your content, you grant us a non-exclusive, sub-licensable, royalty-free, worldwide license to access, use, and display your content in connection with the service and services we provide to you. This license permits us to perform the services that you registered for; for example, it permits us to store your content on redundant data servers, but it *does not* permit us to sell your content to advertisers or display your content other than to those you have authorized to view it, nor does it transfer the copyright to us. This license ends when you delete the material or your account.

**Comment by jennschiffer** [comment]
this looks great - should i create a /privacypolicy page with this as the content?

**Comment by tkellen** [comment]
Ya
