### ISSUE TITLE
Prep Tomato icon for marketplace

### ISSUE THREAD

**Issue by iamjessklein** [bocoup/pombot#8]
We need a tomato avatar/icon for the marketplace.

![screen shot 2016-06-07 at 3 37 57 pm](https://cloud.githubusercontent.com/assets/535012/15872162/0b23605a-2cc6-11e6-9426-f7dda115b996.png)

From the app site: 

> Your app has a high quality, distinctive icon: a 512px by 512px or larger image is required.
> Icons cannot infringe on anyone else's copyright or trademark. If your icon resembles Slackbot or has the Slack icon within it we will ask you to change it.

**Comment by iamjessklein** [comment]
Okay I drew three different directions for the 🍅 tomato. I'd love some feedback:

<img width="850" alt="screen shot 2016-06-14 at 3 36 59 pm" src="https://cloud.githubusercontent.com/assets/535012/16057051/24400fea-3246-11e6-8d82-1d3b9d1f5438.png">

I posted all of the [options in InVision](https://invis.io/HA7N5Q1MF), for a closer look - and I'll throw them up here too: 

Option A:

![option a - searchresults](https://cloud.githubusercontent.com/assets/535012/16057306/80802d98-3247-11e6-8785-74c6e00090f4.png)

Option B:

![optionb](https://cloud.githubusercontent.com/assets/535012/16057317/92254c2c-3247-11e6-9ae4-0f8b1413b9b7.png)

Option C:

![optionc](https://cloud.githubusercontent.com/assets/535012/16057325/9a3b3bce-3247-11e6-8e01-e345f745b4bf.png)

Search Results:

![searchresults](https://cloud.githubusercontent.com/assets/535012/16057329/9fd92924-3247-11e6-9ffb-f43ab0fc8032.png)

**Comment by pamela-drouin** [comment]
I adore option 3. It has the nicest contrast, especially at the smallest size.

**Comment by susanjrobertson** [comment]
I like option A best.

**Comment by jennschiffer** [comment]
i like the first one, especially the colors. can you make it like adorably plump and squishy?

**Comment by pamela-drouin** [comment]
I think option A could work if the contrast of the white in option C is borrowed.

**Comment by jennschiffer** [comment]
here is some pomspiration. i feel like these really portray the personality i've been trying to express through the bot.

![killer-tomato](https://cloud.githubusercontent.com/assets/341305/16057557/a4c51a28-3248-11e6-80df-25193e139c1e.png)
![evil_tomato_by_jv9ufxcy_on_deviantart](https://cloud.githubusercontent.com/assets/341305/16057556/a4c46f2e-3248-11e6-963a-2daa16f16d09.png)
![fefd97p](https://cloud.githubusercontent.com/assets/341305/16057558/a4c75950-3248-11e6-862c-680a1aa8e0db.jpg)

**Comment by iamjessklein** [comment]
Thanks @jennschiffer - I should have come to you HOURS ago for that precedent research

**Comment by iamjessklein** [comment]
I sort of think that version C works best in the smaller size - which is how it will be seen the most (in slack).

**Comment by iros** [comment]
I like Option C the most, in case this is at all helpful for your voting.

Irene Ros
Director of Data Visualization, Bocoup, http://bocoup.com/datavis
Organizer and Program Chair, OpenVis Conf, http://openvisconf.com
irene@bocoup.com

**Comment by isaacdurazo** [comment]
I'm here to say that I like Option 3 a lot! :D

**Comment by boazsender** [comment]
+1 to option C!

These are so great!

**Comment by iamjessklein** [comment]
Okay, I made a few more iterations of v3 - adjusting the color and the green bits. Preference?

![iterations on v3](https://cloud.githubusercontent.com/assets/535012/16084132/9a7f56bc-32e5-11e6-8bed-8259e9e98e12.png)

**Comment by jennschiffer** [comment]
C pls

**Comment by aprilnicolehart** [comment]
#3 !!

**Comment by deathbearbrown** [comment]
C

**Comment by pamela-drouin** [comment]
A

**Comment by isaacdurazo** [comment]
C

**Comment by iamjessklein** [comment]
Great. Thanks everyone! Let's go with Option C:

Here's what it will look like:

![final-appstore](https://cloud.githubusercontent.com/assets/535012/16091241/d0f225b0-3300-11e6-8d7e-5a0bd0a3e50c.png)

![final-searchresults](https://cloud.githubusercontent.com/assets/535012/16091244/d4a65398-3300-11e6-94ba-6f1c2f278295.png)

@jennschiffer : I have the 512 x 512 ready for when we are adding it anywhere.
